server:
  name: "notary-server"
  host: "0.0.0.0"
  port: 7047
  html-info: |
    <h1>Notary Server {version}!</h1>
    <ul>
    <li>git commit hash: <a href="https://github.com/EternisAI/tlsn/commit/{git_commit_hash}">{git_commit_hash}</a></li>
    <li>git commit timestamp: {git_commit_timestamp}</li>
    <li>public key: <pre>{public_key}</pre></li>
    <li>sync state: {sync_state}</li>
    <li>synced key length: {synced_key}</li>
    </ul>
    <a href="/healthcheck">health check</a> - <a href="/info">info</a><br/>

notarization:
  max-transcript-size: 20480

tls:
  enabled: false
  private-key-pem-path: "/app/fixture/tls/notary.key"
  certificate-pem-path: "/app/fixture/tls/notary.crt"

notary-key:
  private-key-pem-path: "/app/fixture/notary/notary.key"
  public-key-pem-path: "/app/fixture/notary/notary.pub"

logging:
  level: DEBUG

authorization:
  enabled: false
  whitelist-csv-path: "/app/fixture/auth/whitelist.csv"

nitriding:
  enabled: true
  host: "127.0.0.1"
  int-port: 8080
  ext-port: 443